services:
  certify-nft-fe:
    container_name: certify-nft-fe
    image: certify-nft-fe:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    restart: always
    networks:
      - certify-nft-network

networks:
  certify-nft-network:
    external: true